"use client";

import { useActionState, useMemo, useState } from "react";

import { applyAiInvitationProposal, createInvitationWithLamma } from "./actions";
import { InvitationRenderer } from "./renderer";
import { initialAiCreatorState, type InvitationModel } from "./types";

export function AiCreator({ invitation }: { invitation: InvitationModel }) {
  const [open, setOpen] = useState(false);
  const [description, setDescription] = useState("");
  const [state, generate, pending] = useActionState(createInvitationWithLamma, initialAiCreatorState);
  const preview = useMemo(() => state.proposal ? { ...invitation, content: { host_names: state.proposal.content.hostNames || null, headline: state.proposal.content.headline || null, invitation_text: state.proposal.content.invitationText || null }, themeConfig: state.proposal.design, sections: invitation.sections.map((section) => ({ ...section, enabled: section.section_type === "hero" || section.section_type === "footer" || state.proposal!.sections.includes(section.section_type) })) } : null, [invitation, state.proposal]);
  if (!open) return <button className="lm-button lm-button-accent mb-6" onClick={() => setOpen(true)} type="button">✨ اصنعها مع لمّة</button>;
  return <section className="lm-panel mb-6 p-5"><div className="flex items-start justify-between gap-4"><div><p className="lm-kicker">اصنعها مع لمّة</p><h2 className="mt-1 text-xl font-bold">احكيلنا عن مناسبتك</h2></div><button className="lm-link" onClick={() => setOpen(false)} type="button">إلغاء</button></div>{!state.proposal ? <form action={generate} className="mt-4"><input name="event_id" type="hidden" value={invitation.event.id} /><textarea className="lm-input min-h-32" dir="auto" maxLength={1200} name="description" onChange={(event) => setDescription(event.target.value)} placeholder="فرحنا أنا ونور يوم 20 ديسمبر، عايزين الدعوة شيك ورومانسية ومش تقليدية..." required value={description} /><button className="lm-button lm-button-accent mt-4" disabled={pending} type="submit">{pending ? "لمّة بتحضّر دعوتك..." : "ابدأ مع لمّة"}</button>{state.error ? <p className="mt-3 text-sm text-red-700">{state.error === "limit" ? "وصلت للحد اليومي للمحاولات. جرّب بكرة." : state.error === "invalid" ? "اكتب وصفًا قصيرًا للمناسبة أولًا." : "مقدرناش نجهز الدعوة دلوقتي. جرّب تاني بعد شوية."}</p> : null}</form> : <div className="mt-5"><div className="grid gap-5 lg:grid-cols-2"><div><p className="font-bold">اقتراح لمّة</p><p className="mt-3 text-lg font-bold" dir="auto">{state.proposal.content.headline}</p><p className="mt-2 whitespace-pre-line text-sm" dir="auto">{state.proposal.content.invitationText}</p></div><div className="overflow-hidden rounded-xl border border-[var(--lm-line)]"><InvitationRenderer invitation={preview!} locale={invitation.event.primary_locale} /></div></div><div className="mt-5 flex flex-wrap gap-3"><form action={applyAiInvitationProposal}><input name="event_id" type="hidden" value={invitation.event.id} /><input name="proposal" type="hidden" value={JSON.stringify(state.proposal)} /><button className="lm-button lm-button-accent" type="submit">تطبيق الاقتراح</button></form><form action={generate}><input name="event_id" type="hidden" value={invitation.event.id} /><input name="description" type="hidden" value={description} /><button className="lm-button lm-button-quiet" disabled={pending} type="submit">جرّب تاني</button></form><button className="lm-button lm-button-quiet" onClick={() => setOpen(false)} type="button">إلغاء</button></div></div>}</section>;
}
