"use client";

import { useState } from "react";

import { changeStoryItem, saveStoryItem } from "./actions";
import type { StoryItem } from "./types";

export function StoryManager({ eventId, items }: { eventId: string; items: StoryItem[] }) {
  const [editing, setEditing] = useState<StoryItem | null>(null);
  return <div className="mt-5 border-t border-[var(--lm-line)] pt-5"><div className="flex items-center justify-between"><div><p className="font-bold">قصتكم</p><p className="text-sm text-[var(--lm-muted)]">ضيفوا لحظة من حكايتكم.</p></div><button className="lm-button lm-button-quiet" onClick={() => setEditing({ id: "", title: "", body: "", date_label: "", position: 0 })} type="button">ضيفوا لحظة</button></div>{editing ? <form action={saveStoryItem} className="mt-4 rounded-xl border border-[var(--lm-line)] p-4"><input name="event_id" type="hidden" value={eventId} />{editing.id ? <input name="story_id" type="hidden" value={editing.id} /> : null}<label className="block text-sm">عنوان اللحظة<input className="lm-input mt-1" defaultValue={editing.title} maxLength={160} name="title" required /></label><label className="mt-3 block text-sm">احكوا اللي حصل<textarea className="lm-input mt-1 min-h-24" defaultValue={editing.body} maxLength={2000} name="body" required /></label><label className="mt-3 block text-sm">تاريخ أو كلمة صغيرة<input className="lm-input mt-1" defaultValue={editing.date_label ?? ""} maxLength={80} name="date_label" /></label><div className="mt-4 flex gap-2"><button className="lm-button lm-button-accent" type="submit">حفظ</button><button className="lm-button lm-button-quiet" onClick={() => setEditing(null)} type="button">إلغاء</button></div></form> : null}<div className="mt-4 space-y-2">{items.map((item) => <div className="rounded-xl border border-[var(--lm-line)] p-3" key={item.id}><p className="font-bold">{item.title}</p><p className="mt-1 text-sm text-[var(--lm-muted)]">{item.date_label}</p><div className="mt-3 flex gap-2"><button className="lm-button lm-button-quiet" onClick={() => setEditing(item)} type="button">تعديل</button>{(["up", "down", "delete"] as const).map((intent) => <form action={changeStoryItem} key={intent}><input name="event_id" type="hidden" value={eventId} /><input name="story_id" type="hidden" value={item.id} /><input name="intent" type="hidden" value={intent} /><button aria-label={intent} className="lm-button lm-button-quiet" type="submit">{intent === "up" ? "↑" : intent === "down" ? "↓" : "حذف"}</button></form>)}</div></div>)}</div></div>;
}
